var config = {
    URLS: {
        GETROOMSOURCES: "https://kc-fengniaowu-talos.kolibre.credit/api/Room/GetRoomSources"
    },
    REGEX: {
        CELLPHONE: /^(10|13|14|15|16|17|18)\d{9}$/,
        PASSWORD: /^[a-zA-Z\d~!@#$%^&*_]{6,18}$/,
        PAYMENT_PASSWORD: /^(?![^a-zA-Z~!@#$%^&*_]+$)(?!\D+$).{8,18}$/,
        URL: /^(?:\w+:)?\/\/([^\s\.]+\.\S{2}|localhost[:?\d]*)\S*$/,
        CREDENTIALNO: /^[1-9]\d{5}[1-9]\d{3}((0\d)|(1[0-2]))(([0|1|2]\d)|3[0-1])\d{3}([0-9]|X|x)$/,
        BANKCARDNO: /^\d{15,19}$/,
        CHECKCODE: /^\d{6}$/,
        FLOOR: /^\d{1,5}$/,
        AMOUNT: /^\d{1,7}(\.\d{1,2})?$/
    },
    MSGINFO: {
        ERROR: "系统服务繁忙，请稍后",
        PHONE: '手机号码不能为空',
        PHONEERR: '手机号码格式错误',
        SEND: '发送成功',
        SENDERR: '发送失败',
        CAPTCHA: '验证码不能为空',
        CAPTCHAERR: '验证码格式错误',
        PASSWORD: '密码不能为空',
        PASSWORDERR: '密码格式错误',
        PASSWORDSAME: '密码不一致,重新输入',
        REGISTER: '注册成功',
        REGISTERERR: '注册失败',
        AGREEMENT1: '请同意蜂鸟屋注册服务协议',
        AGREEMENT2: '请同意蜂鸟屋付房租协议',
        LOGINSUCCESS: '登录成功',
        TOKENERR: '请点击发送验证码',
        REALNAME: "姓名不能为空",
        CREDENTIALNO: "身份证不能为空",
        CREDENTIALNOERR: "身份证号码格式错误",
        IMG1ERR: "身份证正面不能为空",
        IMG2ERR: "身份证背面不能为空",
        VERIFY: "身份证提交成功",
        VERIFYERR: "请提交个人身份信息",
        UPLOADERR: "身份证上传失败",
        RESETPASSWORD: "密码重置成功",
        RESETPASSWORDERR: "密码重置失败",
        SOURCE: "房屋来源不能为空",
        ROOMNUMBER: "房号不能为空",
        FLOOR: "楼层不能为空",
        FLOORERR: "楼层格式错误",
        DECORATION: "朝向不能为空",
        LEASEINFO: "租约信息提交成功",
        OUTERCONTRACTNO: "合同编号不能为空",
        OUTERCONTRACTNOERR: "合同编号格式错误",
        MONTHRENTALAMOUNT: "月租金不能为空",
        MONTHRENTALAMOUNTERR: "月租金格式错误",
        LEASETERM: "剩余月数不能为空",
        LEASETERMERR: "剩余月数格式错误",
        LEASEORDERDAY: "每期付款日不能为空",
        LEASEORDERDAYERR: "每期付款日格式错误",
        LEASEORDERDAYRANG: "输入1~31的数字",
        LEASEEXPIRYTIME: "合同结束日期错误",
        DEPOSITAMOUNT: "押金不能为空",
        DEPOSITAMOUNTERR: "押金格式错误",
        TENEMENTAMOUNTERR: "物业费格式错误",
        POSTDATA: "数据正在提交请稍后",
        IMGCONTRACT2ERR: "合同第2页为空或者上传失败",
        IMGCONTRACT6ERR: "合同第6页为空或者上传失败",
        IMGCONTRACT8ERR: "合同第8页为空或者上传失败",
        IMGIDCARDERR: "本人手持身份证照片为空",
        IMGCONTRACT: "租房合同上传成功",
        IMGIDCARD: "身份证自拍照上传成功",
        LINKREALNAME: "联系人姓名为空",
        LINKCELLPHONE: "联系人手机号为空",
        LINKRELATIONSHIP: "联系人关系为空"
    }
};

module.exports = config;